# Generated by Django 4.2.7 on 2025-11-25 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quran_experience",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="What is your current experience reading the Quran?",
                        max_length=20,
                    ),
                ),
                (
                    "taken_online_lessons",
                    models.BooleanField(
                        help_text="Have you ever taken Quran lessons online?"
                    ),
                ),
                (
                    "online_lessons_reason",
                    models.TextField(blank=True, help_text="Why or why not?"),
                ),
                (
                    "teacher_challenges",
                    models.TextField(
                        help_text="What challenges do you face in finding a qualified teacher?"
                    ),
                ),
                (
                    "time_preference",
                    models.CharField(
                        choices=[
                            ("mornings", "Mornings"),
                            ("evenings", "Evenings"),
                            ("weekends", "Weekends"),
                            ("flexible", "Flexible"),
                        ],
                        help_text="When do you generally have free time to study?",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_session_length",
                    models.IntegerField(
                        choices=[
                            (20, "20 minutes"),
                            (30, "30 minutes"),
                            (45, "45 minutes"),
                            (60, "60 minutes"),
                        ],
                        help_text="How many minutes per session do you prefer?",
                    ),
                ),
                (
                    "preferred_frequency",
                    models.CharField(
                        choices=[
                            ("once_week", "Once a week"),
                            ("twice_week", "Twice a week"),
                            ("more", "More than twice a week"),
                        ],
                        help_text="How often would you like to have sessions?",
                        max_length=20,
                    ),
                ),
                (
                    "fair_price_etb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What is a fair price for a session in ETB?",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "subjects_of_interest",
                    models.JSONField(
                        help_text="Which subjects interest you most? (Quran reading, Tajweed, Hadith, Arabic, Islamic arts)"
                    ),
                ),
                (
                    "trust_factors",
                    models.TextField(
                        help_text="What would make you trust an online teacher? (Ratings, verification, community)"
                    ),
                ),
                (
                    "willing_to_try",
                    models.BooleanField(
                        help_text="If such a platform existed, would you be willing to try it?"
                    ),
                ),
                (
                    "willing_to_try_reason",
                    models.TextField(blank=True, help_text="Why or why not?"),
                ),
                (
                    "desired_features",
                    models.TextField(
                        help_text="What features would make this platform most useful for you?"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Student Survey",
                "verbose_name_plural": "Student Surveys",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_background",
                    models.CharField(
                        choices=[
                            ("madrasa", "Madrasa"),
                            ("mosque", "Mosque"),
                            ("private", "Private"),
                            ("online", "Online"),
                            ("mixed", "Mixed"),
                        ],
                        help_text="What is your teaching background?",
                        max_length=20,
                    ),
                ),
                (
                    "teaching_background_details",
                    models.TextField(
                        blank=True,
                        help_text="Please provide more details about your background",
                    ),
                ),
                (
                    "tried_online_teaching",
                    models.BooleanField(
                        help_text="Have you considered or tried teaching online?"
                    ),
                ),
                (
                    "online_teaching_reason",
                    models.TextField(blank=True, help_text="Why or why not?"),
                ),
                (
                    "teaching_challenges",
                    models.TextField(
                        help_text="What challenges do you face when teaching students now?"
                    ),
                ),
                (
                    "students_per_week",
                    models.IntegerField(
                        help_text="How many students could you realistically teach each week?",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "preferred_session_length",
                    models.IntegerField(
                        choices=[
                            (20, "20 minutes"),
                            (30, "30 minutes"),
                            (45, "45 minutes"),
                            (60, "60 minutes"),
                        ],
                        help_text="What session length do you prefer to teach?",
                    ),
                ),
                (
                    "fair_rate_etb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What rate per session (in ETB) seems fair for you?",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "confident_topics",
                    models.JSONField(
                        help_text="Which Islamic topics do you feel confident teaching?"
                    ),
                ),
                (
                    "would_join_platform",
                    models.BooleanField(
                        help_text="Would you join a platform that handles scheduling and student matching?"
                    ),
                ),
                (
                    "support_needed",
                    models.TextField(
                        help_text="What kind of support would you need to teach effectively online?"
                    ),
                ),
                (
                    "platform_concerns",
                    models.TextField(
                        blank=True,
                        help_text="What concerns do you have about using an online teaching platform?",
                    ),
                ),
                (
                    "feedback_preferences",
                    models.TextField(
                        help_text="How do you think students' feedback should be collected and shown?"
                    ),
                ),
                (
                    "wants_early_access",
                    models.BooleanField(
                        help_text="Would you like early access to test and teach on this platform?"
                    ),
                ),
                (
                    "early_access_contact",
                    models.EmailField(
                        blank=True,
                        help_text="Email for early access (optional)",
                        max_length=254,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Teacher Survey",
                "verbose_name_plural": "Teacher Surveys",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
