# Generated by Django 4.2.7 on 2025-11-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsurvey",
            name="phone_number",
            field=models.CharField(
                default=251911223344,
                help_text="Phone number for identity verification (e.g., +251...)",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teachersurvey",
            name="phone_number",
            field=models.CharField(
                default=251922334455,
                help_text="Phone number for identity verification (e.g., +251...)",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
