# Generated by Django 4.2.7 on 2025-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_studentsurvey_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for identity verification (e.g., +251...)",
                max_length=15,
                null=True,
            ),
        ),
    ]
