# Generated by Django 4.2.7 on 2025-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_alter_studentsurvey_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for identity verification (e.g., +251...)",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="teachersurvey",
            name="phone_number",
            field=models.CharField(
                help_text="Phone number for identity verification (e.g., +251...)",
                max_length=15,
                unique=True,
            ),
        ),
    ]
