# Generated by Django 4.2.7 on 2025-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_alter_studentsurvey_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentsurvey",
            options={},
        ),
        migrations.AlterModelOptions(
            name="teachersurvey",
            options={},
        ),
        migrations.AlterField(
            model_name="studentsurvey",
            name="desired_features",
            field=models.TextField(
                blank=True, help_text="What features would you like to see?"
            ),
        ),
        migrations.AlterField(
            model_name="teachersurvey",
            name="early_access_contact",
            field=models.CharField(
                blank=True,
                help_text="Contact info for early access (if different from phone)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="teachersurvey",
            name="wants_early_access",
            field=models.BooleanField(
                default=False, help_text="Would you be interested in early access?"
            ),
        ),
    ]
