# Generated by Django 5.2.6 on 2025-11-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_alter_studentsurvey_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsurvey",
            name="full_name",
            field=models.CharField(
                default="", help_text="Full name of the student", max_length=255
            ),
        ),
    ]
