# Generated by Django 4.2.7 on 2025-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0006_studentsurvey_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsurvey",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("8-15", "8-15"),
                    ("15-24", "15-24"),
                    ("24-32", "24-32"),
                    ("32-40", "32-40"),
                    ("40+", "40+"),
                ],
                default="15-24",
                help_text="Age range of the student",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="teachersurvey",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("8-15", "8-15"),
                    ("15-24", "15-24"),
                    ("24-32", "24-32"),
                    ("32-40", "32-40"),
                    ("40+", "40+"),
                ],
                default="24-32",
                help_text="Age range of the teacher",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="teachersurvey",
            name="full_name",
            field=models.CharField(
                default="", help_text="Full name of the teacher", max_length=255
            ),
        ),
    ]
