# Generated by Django 4.2.7 on 2025-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0007_studentsurvey_age_range_teachersurvey_age_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsurvey",
            name="dynamic_responses",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Responses to dynamic questions based on interests",
            ),
        ),
        migrations.AddField(
            model_name="teachersurvey",
            name="dynamic_responses",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Responses to dynamic questions based on confident topics",
            ),
        ),
    ]
