# Generated by Django 4.2.7 on 2025-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_studentsurvey_dynamic_responses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsurvey",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                help_text="Gender",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="teachersurvey",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                help_text="Gender",
                max_length=10,
            ),
        ),
    ]
