# Generated by Django 4.2.7 on 2025-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_studentsurvey_gender_teachersurvey_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="quran_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                help_text="What is your current experience reading the Quran?",
                max_length=20,
                null=True,
            ),
        ),
    ]
