# Generated by Django 4.2.7 on 2025-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0010_alter_studentsurvey_quran_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_type",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        max_length=10,
                    ),
                ),
                ("section", models.CharField(max_length=50)),
                ("identifier", models.CharField(max_length=50)),
                ("text_en", models.TextField()),
                ("text_ar", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("choice", "Multiple Choice"), ("text", "Text Input")],
                        default="choice",
                        max_length=20,
                    ),
                ),
                ("options_en", models.JSONField(blank=True, default=list)),
                ("options_ar", models.JSONField(blank=True, default=list)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("survey_type", "identifier")},
            },
        ),
    ]
